#!/bin/bash
echo "Beginning mesh generation"

if [ -d "$2$1-3D" ]; then
	echo "Copying 3D files" 
	cp $2$1-3D/$1-3D.ply .
fi

if [ -d "$2$13D" ]; then
	echo "Copying 3D files"
	cp $2$13D/$13D.ply $1-3D.ply
fi

if [ ! -d "tmp"]; then
	mkdir tmp;
fi

echo "Grabbing and converting DNGs"
scripts/composeShell $1 $3

echo "Masking vertices"
OUTPUT=`bin/meshlabserver -i $1-3D.ply -o converted_$1.obj`
bin/applyMask converted_$1.obj $1.png > mask_$1.obj

OUTPUT=`bin/meshlabserver -i mask_$1.obj -o normals_$1.ply -s scripts/getNormals.mlx`

echo "Formatting ply"
bin/removeHead normals_$1.ply $1

if [ -f "headOut_$1.ply" ]; then
	echo "Running reconstruction"
	bin/PoissonRecon.64 --in headOut_$1.ply --out recon_$1.ply --binary
fi

echo "Cleaning mesh"
OUTPUT=`bin/meshlabserver -i recon_$1.ply -o $1-mesh.obj -s scripts/cleanUp.mlx`

echo "Flattening texture image"
bin/flatten flatfield.png $1.png $1_flat.png

echo "Adding Texture"
bin/texture $1-mesh.obj $1_flat.png $1.obj.mtl > $1.obj

echo "Cleaning up"
mv $1.obj tmp
mv $1.obj.mtl tmp
mv $1_flat.png tmp
rm $1.png
rm normals_$1.ply headOut_$1.ply recon_$1.ply converted_$1.obj mask_$1.obj $1-3D.ply $1-mesh.obj
