#!/bin/bash

BORDER=20
BUFFER=175

if [ $# -lt 1 ]; then
	echo "Usage: cropToLargest <Directory> [<Out Directory>]"
	exit 0;
fi

echo "Finding largest page size"
DIR=$1

if [ $# -gt 1 ]; then
	OUTDIR=$2
else
	OUTDIR=$DIR
fi

WMAX=0
HMAX=0

NUMFILES=`ls $DIR*.png | wc -l`
COUNTER=1


for f in $DIR*.png
do
	echo "Finding size for image $COUNTER of $NUMFILES"
	SIZE=`./findPageSize $f`
	set $SIZE
	if [ $6 -gt $WMAX ]; then
		let WMAX=$6
	fi
	if [ $8 -gt $HMAX ]; then
		if [ $4 -gt $BUFFER ]; then
			let HMAX=$8
		else
			echo "Ignoring bad threshold"
		fi
	fi
	let COUNTER=$COUNTER+1
done

echo "Largest Size: $WMAX X $HMAX"
echo "Cropping images with a $BORDER pixel border"

let HMAX=$HMAX+$BORDER
let WMAX=$WMAX+$BORDER

let COUNTER=1
for f in $DIR*.png
do
	echo "Cropping image $COUNTER of $NUMFILES"
	./cropToPage $f -w $WMAX -h $HMAX
	let COUNTER=$COUNTER+1
done

if [ $OUTDIR != $DIR ]; then
	echo "Transferring images to $OUTDIR"
	mv $DIR*_crop.png $OUTDIR
fi
