#!/bin/bash

BORDER=20
BUFFER=175

if [ $# -lt 1 ]; then
	echo "Usage: cropToLargest <Directory> [<Out Directory>]"
	exit 0;
fi

echo "Finding largest page size"
DIR=$1

if [ $# -gt 1 ]; then
	OUTDIR=$2
else
	OUTDIR=$DIR
fi

WMAX=0
HMAX=0

NUMFILES=`ls $DIR*.png | wc -l`
COUNTER=1


for f in $DIR*.png
do
	echo "Finding size for image $COUNTER of $NUMFILES"
	SIZE=`./findPageSize $f`
	if [ "$SIZE" != "" ]; then
		echo "$SIZE"
		set $SIZE
		TFLAG=1
		if [ $2 -lt 0 ]; then
			let TFLAG=0
		fi
		if [ $4 -lt 0 ]; then
			let TFLAG=0
		fi
		if [ $6 -lt 0 ]; then
			let TFLAG=0
		fi
		if [ $8 -lt 0 ]; then
			let TFLAG=0
		fi
		if [ $6 -gt 7200 ];then
			let TFLAG=0
		fi
		if [ $8 -gt 5800 ]; then
			let TFLAG=0
		fi

		if [ $TFLAG -eq 0 ]; then
			echo "Ignoring bad threshold"
		else
			WIDTHS[$COUNTER]=$6
			HEIGHTS[$COUNTER]=$8
		fi
	fi
	let COUNTER=$COUNTER+1
done

echo "Input any image numbers to remove incorrect sizes"
echo "(q to quit and continue to cropping)"
read INPUT
while [ "$INPUT" != "q" ]
do
	WIDTHS[$INPUT]=0
	HEIGHTS[$INPUT]=0
	echo "Image $INPUT removed"
	read INPUT
done
for width in ${WIDTHS[@]}
do
	if [ $width -gt $WMAX ]; then
		let WMAX=$width
	fi
done
for height in ${HEIGHTS[@]}
do
	if [ $height -gt $HMAX ]; then
		let HMAX=$height
	fi
done

echo "Largest Size: $WMAX X $HMAX"
echo "Cropping images with a $BORDER pixel border"


let COUNTER=1
for f in $DIR*.png
do
	cutf=${f/$DIR/}
	cropf=${cutf/.png/_crop.png}
	outf=$OUTDIR$cropf
	echo "Cropping image $COUNTER of $NUMFILES"
	./cropToPage $f -w $WMAX -h $HMAX -o $outf -b $BORDER
	let COUNTER=$COUNTER+1
done

