#!/bin/bash

BORDER=20
BUFFER=175

if [ $# -lt 1 ]; then
	echo "Usage: cropToLargest <Directory> [<Out Directory>]"
	exit 0;
fi

echo "Finding largest page size"
DIR=$1

if [ $# -gt 1 ]; then
	OUTDIR=$2
else
	OUTDIR=$DIR
fi

WMAX=0
HMAX=0

NUMFILES=`ls $DIR*.png | wc -l`
COUNTER=1


for f in $DIR*.png
do
	echo "Finding size for image $COUNTER of $NUMFILES"
	SIZE=`./findPageSize $f`
	if [ "$SIZE" != "" ]; then
		echo "$SIZE"
		set $SIZE
		TFLAG=1
		if [ $2 -lt 0 ]; then
			let TFLAG=0
		fi
		if [ $4 -lt 0 ]; then
			let TFLAG=0
		fi
		if [ $6 -lt 0 ]; then
			let TFLAG=0
		fi
		if [ $8 -lt 0 ]; then
			let TFLAG=0
		fi
		if [ $6 -gt 7200 ];then
			let TFLAG=0
		fi
		if [ $8 -gt 5800 ]; then
			let TFLAG=0
		fi

		if [ $TFLAG -eq 0 ]; then
			echo "Ignoring bad threshold"
		else
			if [ $6 -gt $WMAX ]; then
				let WMAX=$6
			fi
			if [ $8 -gt $HMAX ]; then
				let HMAX=$8
			fi
		fi
	fi
	let COUNTER=$COUNTER+1
done

echo "Largest Size: $WMAX X $HMAX"
echo "Cropping images with a $BORDER pixel border"

let HMAX=$HMAX+$BORDER
let WMAX=$WMAX+$BORDER

let COUNTER=1
for f in $DIR*.png
do
	cutf=${f/$DIR/}
	cropf=${cutf/.png/_crop.png}
	outf=$OUTDIR$cropf
	echo "Cropping image $COUNTER of $NUMFILES"
	./cropToPage $f -w $WMAX -h $HMAX -o $outf
	let COUNTER=$COUNTER+1
done

